- hosts: jboss_eap_rhel_hosts
  remote_user: "{{ ansible_rhel_user }}"
  sudo: true
  gather_facts: true

  vars_prompt:
    - name: "rhn_username"
      prompt: "Enter Your Red Hat Customer Portal Username"
      private: no

    - name: "rhn_password"
      prompt: "Enter Your Red Hat Customer Portal Password"
      private: yes

  pre_tasks:
  - name: Subscribe the host
    redhat_subscription:
      state: present
      username: "{{ rhn_username }}"
      password: "{{ rhn_password }}"
      autosubscribe: true
    tags:
    - jboss_eap

  - name: Install Java
    action: "{{ ansible_pkg_mgr }} name={{ eap_java_pkg_name }} state=latest"
    tags:
    - jboss_eap

  - name: Install Unzip
    action: "{{ ansible_pkg_mgr }} name=unzip state=latest"
    tags:
    - jboss_eap

  - name: Enable Optional Repo
    command: "subscription-manager repos --enable rhel-7-server-optional-rpms"
    tags:
    - jboss_eap

  - name: Enable Extras Repo
    command: "subscription-manager repos --enable rhel-7-server-extras-rpms"
    tags:
    - jboss_eap

  - name: Download EPEL
    get_url:
      url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
      dest: "/tmp"
    tags:
    - jboss_eap

  - name: Install EPEL
    action: "{{ ansible_pkg_mgr }} name=/tmp/epel-release-latest-7.noarch.rpm state=present"
    tags:
    - jboss_eap

  - name: Install PIP (which requires EPEL)
    action: "{{ ansible_pkg_mgr }} name=python-pip state=latest"
    tags:
    - jboss_eap

  - name: Install Python Dependencies
    action: "pip name={{item}} state=present"
    with_items:
       - requests
       - lxml
    tags:
    - jboss_eap

  roles:
  - role: jboss_eap
